name: 'TestPlugin'
description: 'A test plugin for ArctLib'
version: '1.0.0'
api-version: '1.14'
main: 'io.arct.testplugin.TestPlugin'

softdepend:
  - 'ArctCore'

commands:
  simple:
    description: 'Test Basic Functionality'
  ui:
    description: 'Test GUI Functionality'
  config:
    description: 'Test Configuration Functionality'
  tabcomplete:
    description: 'Test Tab Completion Functionality'